name: nutrient_scanner
description: "nutrient scanner"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  openai_dart: ^0.4.5
  envied: ^1.1.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  simple_barcode_scanner: ^0.3.0
  camera: ^0.11.0+2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/images/
      - assets/icons/