name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Java 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter 설치
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 의존성 설치
        run: flutter pub get

      - name: OpenAI API 키 설정
        run: echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> $GITHUB_ENV

      - name: APK 빌드
        run: flutter build apk --release

      - name: 빌드 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
