name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Java 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter 설치
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 의존성 설치
        run: flutter pub get

      - name: 코드 포맷 확인
        run: flutter format --set-exit-if-changed .

      - name: 코드 분석
        run: flutter analyze

      - name: 테스트 실행
        run: flutter test

      - name: APK 빌드
        run: flutter build apk --release

      - name: 빌드 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
